### PR TITLE
Padding setting was added to tweak UIs with small padding on the righ…

### PR DESCRIPTION
**Pull request by antonbrams**
a small improovement for right side padding, because of small padding by some UI-Themes. (its not for nuclide, because i don't use it and can't test)

### CODE REVIEW

**Comment by antonbrams** [comment]
and please test it, im not sure, that it works properly

**Comment by dikamilo** [comment]
To make this work you should add `@pad` also here:

```
if currWidth > @treeView.width()
        @treeView.animate {width: @getWidth(currWidth + @pad)}, 200
```

in `resizeTreeView` and `resizeNuclideFileTree`  and in `resizeNuclideFileTree`:

```
newWidth = fileTree.find('.nuclide-file-tree').outerWidth() + @pad
```

**Comment by lexcast** [comment]
@antonkluev there is something wrong with the package.json

**Review by lexcast — CHANGES_REQUESTED** [review]
the package.json is wrong

**Comment by bradykeeling** [comment]
Requested pull request with fix here: https://github.com/lexcast/tree-view-autoresize/pull/6

**Pull request closed without merging**
